[package]
name = "vince"
version = "0.1.0"
edition = "2021"
authors = ["Louise Montalvo <louanmontalvo@gmail.com>"]
license = "MIT"
description = "An audio-video synthesizer"
readme = true
repository = "https://github.com/lwizchz/vince"
keywords = ["audio", "video", "synth", "dsp"]

[profile.dev]
opt-level = 3

[profile.release]
lto = true
codegen-units = 1

[dependencies]
bevy = { version = "0.10.1", features = ["dynamic_linking"] }
bevy_common_assets = { version = "0.6.0", features = ["toml"] }
bevy_framepace = "0.12.1"
cpal = "0.15.2"
oddio = "0.6.2"
rand = "0.8.5"
screenshots = { git = "https://github.com/lwizchz/screenshots-rs", optional = true }
serde = "1.0.163"
typetag = "0.2.8"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5"

[features]
default = ["video_in"]
video_in = ["dep:screenshots"]
