[modules]
0M = { type = "AudioOut", knobs = [0.1] }

1M = { type = "Oscillator", func = "Sine", knobs = [0.0, 440.0, 1.0, 0.0] }
2M = { type = "Oscilloscope" }

[patches]
1M0O = [
    "0M0I",
    "2M0I",
]
