[info]
name = "Hopefully (drums)"
author = "Louise Montalvo <louanmontalvo@gmail.com>"

[modules]
0M = { type = "AudioOut", knobs = [1.0] }

1M = { type = "Sampler", samples = [
        [
            "assets/sounds/808-aristocrat/kick.wav",
            [
                [0.0, 1.0],

                [8.0, 1.0],

                [16.0, 1.0],

                [24.0, 1.0],
            ],
        ],
        [
            "assets/sounds/808-aristocrat/snare.wav",
            [
                [1.0, 1.0],
                [3.0, 1.0],
                [5.0, 1.0],
                [7.0, 1.0],

                [9.0, 1.0],
                [11.0, 1.0],
                [13.0, 1.0],
                [15.0, 1.0],

                [17.0, 1.0],
                [19.0, 1.0],
                [21.0, 1.0],
                [23.0, 1.0],

                [25.0, 1.0],
                [27.0, 1.0],
                [29.0, 1.0],
                [31.0, 1.0],
            ],
        ],
        [
            "assets/sounds/808-aristocrat/tom-mid.wav",
            [

            ],
        ],
        [
            "assets/sounds/808-aristocrat/hat-closed.wav",
            [
                [0.00, 1.0],
                [0.25, 1.0],
                [0.50, 1.0],
                [0.75, 1.0],
                [1.00, 1.0],
                [1.25, 1.0],
                [1.50, 1.0],
                [1.75, 1.0],
                [2.00, 1.0],
                [2.25, 1.0],
                [2.50, 1.0],
                [2.75, 1.0],
                [3.00, 1.0],
                [3.25, 1.0],
                [3.50, 1.0],
                [3.75, 1.0],
                [4.00, 1.0],
                [4.25, 1.0],
                [4.50, 1.0],
                [4.75, 1.0],
                [5.00, 1.0],
                [5.25, 1.0],
                [5.50, 1.0],
                [5.75, 1.0],
                [6.00, 1.0],
                [6.25, 1.0],
                [6.50, 1.0],
                [6.75, 1.0],
                [7.00, 1.0],
                [7.25, 1.0],
                [7.50, 1.0],

                [8.00, 1.0],
                [8.25, 1.0],
                [8.50, 1.0],
                [8.75, 1.0],
                [9.00, 1.0],
                [9.25, 1.0],
                [9.50, 1.0],
                [9.75, 1.0],
                [10.00, 1.0],
                [10.25, 1.0],
                [10.50, 1.0],
                [10.75, 1.0],
                [11.00, 1.0],
                [11.25, 1.0],
                [11.50, 1.0],
                [11.75, 1.0],
                [12.00, 1.0],
                [12.25, 1.0],
                [12.50, 1.0],
                [12.75, 1.0],
                [13.00, 1.0],
                [13.25, 1.0],
                [13.50, 1.0],
                [13.75, 1.0],
                [14.00, 1.0],
                [14.25, 1.0],
                [14.50, 1.0],
                [14.75, 1.0],
                [15.00, 1.0],
                [15.25, 1.0],
                [15.50, 1.0],

                [16.00, 1.0],
                [16.25, 1.0],
                [16.50, 1.0],
                [16.75, 1.0],
                [17.00, 1.0],
                [17.25, 1.0],
                [17.50, 1.0],
                [17.75, 1.0],
                [18.00, 1.0],
                [18.25, 1.0],
                [18.50, 1.0],
                [18.75, 1.0],
                [19.00, 1.0],
                [19.25, 1.0],
                [19.50, 1.0],
                [19.75, 1.0],
                [20.00, 1.0],
                [20.25, 1.0],
                [20.50, 1.0],
                [20.75, 1.0],
                [21.00, 1.0],
                [21.25, 1.0],
                [21.50, 1.0],
                [21.75, 1.0],
                [22.00, 1.0],
                [22.25, 1.0],
                [22.50, 1.0],
                [22.75, 1.0],
                [23.00, 1.0],
                [23.25, 1.0],
                [23.50, 1.0],

                [24.00, 1.0],
                [24.25, 1.0],
                [24.50, 1.0],
                [24.75, 1.0],
                [25.00, 1.0],
                [25.25, 1.0],
                [25.50, 1.0],
                [25.75, 1.0],
                [26.00, 1.0],
                [26.25, 1.0],
                [26.50, 1.0],
                [26.75, 1.0],
                [27.00, 1.0],
                [27.25, 1.0],
                [27.50, 1.0],
                [27.75, 1.0],
                [28.00, 1.0],
                [28.25, 1.0],
                [28.50, 1.0],
                [28.75, 1.0],
                [29.00, 1.0],
                [29.25, 1.0],
                [29.50, 1.0],
                [29.75, 1.0],
                [30.00, 1.0],
                [30.25, 1.0],
                [30.50, 1.0],
                [30.75, 1.0],
                [31.00, 1.0],
                [31.25, 1.0],
                [31.50, 1.0],
            ],
        ],
        [
            "assets/sounds/808-aristocrat/hat-open.wav",
            [
                [7.75, 1.0],

                [15.75, 1.0],

                [23.75, 1.0],

                [31.75, 1.0],
            ],
        ],
        [
            "assets/sounds/808-aristocrat/cymbal-soft.wav",
            [

            ],
        ],
    ], knobs = [160.0, 32.0] }
2M = { name = "Kick", type = "Oscilloscope" }
3M = { name = "Snare", type = "Oscilloscope" }
4M = { name = "Tom Mid", type = "Oscilloscope" }
5M = { name = "Hat Closed", type = "Oscilloscope" }
6M = { name = "Hat Open", type = "Oscilloscope" }
7M = { name = "Cymbal Soft", type = "Oscilloscope" }

8M = { type = "Mixer", knobs = [1.0, 1.0] }
9M = { type = "Mixer", knobs = [1.0, 1.0] }
10M = { type = "Mixer", knobs = [1.0, 1.0] }
11M = { type = "Mixer", knobs = [1.0, 1.0] }
12M = { type = "Mixer", knobs = [1.0, 1.0] }

[patches]
1M0O = [
    "2M0I",
    "8M0I",
]
1M1O = [
    "3M0I",
    "8M1I",
]
1M2O = [
    "4M0I",
    "9M0I",
]
1M3O = [
    "5M0I",
    "9M1I",
]
1M4O = [
    "6M0I",
    "10M0I",
]
1M5O = [
    "7M0I",
    "10M1I",
]
8M0O = [
    "11M0I",
]
9M0O = [
    "11M1I",
]
10M0O = [
    "12M0I",
]
11M0O = [
    "12M1I",
]
12M0O = [
    "0M0I",
]
