[modules]
0M = { type = "AudioOut", knobs = [1.0] }

1M = { type = "FileDecoder", filename = "assets/sounds/mono_test.wav", knobs = [1.0] }

2M = { type = "Equalizer", knobs = [100.0, 10.0, 2.0] }
3M = { type = "Oscilloscope" }

4M = { type = "Compressor", knobs = [0.25, 0.5, 0.0] }
5M = { type = "Oscilloscope" }

6M = { type = "Oscillator", func = "Triangle", knobs = [2.0, 0.125, 2.0, 0.0] }
7M = { type = "Delay", knobs = [0.5, 0.75, 0.5] }
8M = { type = "Panner", knobs = [0.4] }

[patches]
1M0O = [
    "2M0I",
]
2M0O = [
    "3M0I",
    "4M0I",
]
4M0O = [
    "5M0I",
    "7M0I",
]
6M0O = [
    "7M0K",
]
7M0O = [
    "8M0I",
]
8M0O = [
    "0M0I",
]
8M1O = [
    "0M1I",
]
