[modules]
0M = { type = "AudioOut", knobs = [0.1] }

1M = { type = "FileDecoder", filename = "assets/sounds/stereo_test.wav", knobs = [1.0] }
2M = { type = "Mixer", knobs = [
        0.5, # Left channel
        0.5, # Right channel
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
    ] }

3M = { type = "Equalizer", knobs = [1000.0, 10.0, 5.0] }
4M = { type = "Oscilloscope" }

[patches]
1M0O = [
    "2M0I",
]
1M1O = [
    "2M1I",
]
2M0O = [
    "3M0I",
]
3M0O = [
    "0M0I",
    "4M0I",
]
