[info]
mode = "Video"

[modules]
0M = { name = "RGB Video", type = "ComponentVideoOut" }
1M = { name = "Luma Video", type = "CompositeVideoOut" }

2M = { name = "Screen Record", type = "VideoIn", source = "Screen" }
3M = { name = "Red", type = "Oscilloscope" }
4M = { name = "Green", type = "Oscilloscope" }
5M = { name = "Blue", type = "Oscilloscope" }

6M = { type = "Luma" }
7M = { name = "Luma", type = "Oscilloscope" }

[patches]
2M0O = [
    "0M0I",
    "3M0I",
    "6M0I",
]
2M1O = [
    "0M1I",
    "4M0I",
    "6M1I",
]
2M2O = [
    "0M2I",
    "5M0I",
    "6M2I",
]
6M0O = [
    "1M0I",
    "7M0I",
]
