[modules]
0M = { name = "Audio Out", type = "AudioOut", knobs = [1.0] }

1M = { type = "FileDecoder", filename = "assets/sounds/stereo_test.wav", knobs = [1.0] }

2M = { type = "Equalizer", knobs = [50.0, 20.0, 2.0] }
3M = { type = "Equalizer", knobs = [50.0, 20.0, 2.0] }

4M = { name = "Left Audio", type = "Oscilloscope" }
5M = { name = "Right Audio", type = "Oscilloscope" }

[patches]
1M0O = [
    "2M0I",
]
1M1O = [
    "3M0I",
]
2M0O = [
    "0M0I",
    "4M0I",
]
3M0O = [
    "0M1I",
    "5M0I",
]
