[info]
mode = "Video"
description = "To make this rack work, add your own greenscreen test video at the below path."

[modules]
0M = { type = "ComponentVideoOut", is_own_window = true }
1M = { type = "FileEncoder", filename = "target/greenscreen.y4m" }

2M = { type = "FileDecoder", filename = "assets/videos/greenscreen.y4m", knobs = [1.0] }
3M = { type = "ChromaKey", knobs = [0.5] }

4M = { type = "Oscillator", func = "Saw", sync = "Vertical", knobs = [0.0, 100.0, 0.75, 0.0] }
5M = { type = "Oscillator", func = "Sine", knobs = [0.75, 2000000.0, 0.25, 0.0] }
6M = { type = "Oscillator", func = "Triangle", knobs = [9000.0, 1.0, 200.0, 0.0] }

[patches]
2M0O = [
    "3M0I",
]
2M1O = [
    "3M1I",
]
2M2O = [
    "3M2I",
]
3M0O = [
    "0M0I",
    "1M0I",
]
3M1O = [
    "0M1I",
    "1M1I",
]
3M2O = [
    "0M2I",
    "1M2I",
]
4M0O = [
    "3M4I",
]
5M0O = [
    "3M3I",
    "4M2K",
]
6M0O = [
    "4M1K",
]
