[modules]
0M = { name = "Audio Out", type = "AudioOut", knobs = [1.0] }

1M = { type = "FileDecoder", filename = "assets/sounds/stereo_test.wav", knobs = [1.0] }
2M = { name = "Left Audio", type = "Oscilloscope" }
3M = { name = "Right Audio", type = "Oscilloscope" }

[patches]
1M0O = [
    "0M0I",
    "2M0I",
]
1M1O = [
    "0M1I",
    "3M0I",
]
