[info]
mode = "Video"

[modules]
0M = { type = "ComponentVideoOut" }

1M = { type = "Oscillator", func = "Sine", sync = "Horizontal", knobs = [0.5, 100.0, 0.5, 0.0] }
2M = { type = "Oscillator", func = "Sine", sync = "Vertical", knobs = [0.75, 20000.0, 0.25, 0.0] }
3M = { type = "Oscillator", func = "Sine", knobs = [90.0, 0.1, 10.0, 0.0] }

4M = { type = "Noise", knobs = [0.1] }
5M = { type = "Brightness", knobs = [-0.04] }

6M = { type = "Contrast", knobs = [0.03] }

[patches]
1M0O = [
    "6M0I",
]
2M0O = [
    "0M2I",
    "1M2K",
]
3M0O = [
    "1M1K",
]
4M0O = [
    "5M0I",
]
5M0O = [
    "0M1I",
]
6M0O = [
    "0M0I",
]
