[info]
name = "No Longer Need You Fight"
author = "Louise Montalvo <louanmontalvo@gmail.com>"

[modules]
0M = { type = "AudioOut", knobs = [0.1] }
1M = { type = "Mixer", knobs = [
        1.0, # Kick
        1.0, # Snare
        1.0, # Tom Mid
        1.0, # Hat Closed
        1.0, # Hat Open
        1.0, # Cymbal Soft
        0.9, # Bass
        0.3, # Lead
    ] }

2M = { name = "Drum Sampler", type = "MultiSampler", samplers = [
        [
            { name = "Verse", type = "Sampler", samples = [
                [
                    "assets/sounds/808-aristocrat/kick.wav",
                    [
                        [0.00, 1.0],
                        [0.50, 1.0],

                        [3.00, 1.0],
                        [3.50, 1.0],

                        [6.00, 1.0],
                        [6.50, 1.0],

                        [9.00, 1.0],
                        [9.50, 1.0],

                        [12.00, 1.0],
                        [12.50, 1.0],
                    ],
                ],
                [
                    "assets/sounds/808-aristocrat/snare.wav",
                    [
                        [1.00, 1.0],

                        [4.00, 1.0],

                        [6.00, 1.0],
                        [6.50, 1.0],
                        [7.00, 1.0],

                        [10.00, 1.0],

                        [12.00, 1.0],
                        [12.25, 1.0],
                        [12.50, 1.0],
                        [12.75, 1.0],
                        [13.00, 1.0],
                        [13.25, 1.0],
                        [13.50, 1.0],
                    ],
                ],
                [
                    "assets/sounds/808-aristocrat/tom-mid.wav",
                    [
                        [0.00, 1.0],
                        [0.50, 1.0],

                        [3.00, 1.0],
                        [3.50, 1.0],

                        [9.00, 1.0],
                        [9.50, 1.0],
                    ],
                ],
                [
                    "assets/sounds/808-aristocrat/hat-closed.wav",
                    [
                        [0.25, 0.25],
                        [0.75, 0.25],
                        [1.25, 0.25],
                        [1.75, 0.25],
                        [2.25, 0.25],
                        [2.75, 0.25],

                        [3.25, 0.25],
                        [3.75, 0.25],
                        [4.25, 0.25],
                        [4.75, 0.25],
                        [5.25, 0.25],
                        [5.75, 0.25],

                        [6.25, 0.25],
                        [6.75, 0.25],
                        [7.25, 0.25],
                        [7.75, 0.25],
                        [8.25, 0.25],
                        [8.75, 0.25],

                        [9.25, 0.25],
                        [9.75, 0.25],
                        [10.25, 0.25],
                        [10.75, 0.25],
                        [11.25, 0.25],
                        [11.75, 0.25],

                        [12.25, 0.25],
                        [12.75, 0.25],
                        [13.25, 0.25],
                    ],
                ],
                [
                    "assets/sounds/808-aristocrat/hat-open.wav",
                    [
                        [0.00, 1.0],
                        [0.50, 1.0],
                        [1.00, 1.0],
                        [1.50, 1.0],
                        [2.00, 1.0],
                        [2.50, 1.0],

                        [3.00, 1.0],
                        [3.50, 1.0],
                        [4.00, 1.0],
                        [4.50, 1.0],
                        [5.00, 1.0],
                        [5.50, 1.0],

                        [6.00, 1.0],
                        [6.50, 1.0],
                        [7.00, 1.0],
                        [7.50, 1.0],
                        [8.00, 1.0],
                        [8.50, 1.0],

                        [9.00, 1.0],
                        [9.50, 1.0],
                        [10.00, 1.0],
                        [10.50, 1.0],
                        [11.00, 1.0],
                        [11.50, 1.0],

                        [12.00, 1.0],
                        [12.50, 1.0],
                        [13.00, 1.0],
                    ],
                ],
                [
                    "assets/sounds/808-aristocrat/cymbal-soft.wav",
                    [
                        [13.50, 1.0],
                        [14.00, 1.0],
                        [14.50, 1.0],
                    ],
                ],
            ], knobs = [140.0, 15.0] },
            4.0,
        ],
        [
            { name = "Chorus", type = "Sampler", samples = [
                [
                    "assets/sounds/808-aristocrat/kick.wav",
                    [
                        [0.00, 1.0],
                        [0.50, 1.0],

                        [3.00, 1.0],
                        [3.50, 1.0],

                        [6.00, 1.0],
                        [6.50, 1.0],

                        [9.00, 1.0],
                        [9.50, 1.0],

                        [12.00, 1.0],
                        [12.50, 1.0],
                    ],
                ],
                [
                    "assets/sounds/808-aristocrat/snare.wav",
                    [
                        [1.00, 1.0],

                        [4.00, 1.0],

                        [6.00, 1.0],
                        [6.50, 1.0],
                        [7.00, 1.0],

                        [10.00, 1.0],

                        [12.00, 1.0],
                        [12.25, 1.0],
                        [12.50, 1.0],
                        [12.75, 1.0],
                        [13.00, 1.0],
                        [13.25, 1.0],
                        [13.50, 1.0],
                        [14.00, 1.0],
                        [14.50, 1.0],
                    ],
                ],
                [
                    "assets/sounds/808-aristocrat/tom-mid.wav",
                    [
                        [0.00, 1.0],
                        [0.50, 1.0],

                        [3.00, 1.0],
                        [3.50, 1.0],

                        [9.00, 1.0],
                        [9.50, 1.0],
                    ],
                ],
                [
                    "assets/sounds/808-aristocrat/hat-closed.wav",
                    [
                        [0.00, 1.0],
                        [0.25, 1.0],
                        [0.50, 1.0],
                        [0.75, 1.0],
                        [1.00, 1.0],
                        [1.25, 1.0],
                        [1.50, 1.0],
                        [1.75, 1.0],
                        [2.00, 1.0],
                        [2.25, 1.0],
                        [2.50, 1.0],
                        [2.75, 1.0],

                        [3.00, 1.0],
                        [3.25, 1.0],
                        [3.50, 1.0],
                        [3.75, 1.0],
                        [4.00, 1.0],
                        [4.25, 1.0],
                        [4.50, 1.0],
                        [4.75, 1.0],
                        [5.00, 1.0],
                        [5.25, 1.0],
                        [5.50, 1.0],
                        [5.75, 1.0],

                        [7.50, 1.0],
                        [7.75, 1.0],
                        [8.00, 1.0],
                        [8.25, 1.0],
                        [8.50, 1.0],
                        [8.75, 1.0],

                        [9.00, 1.0],
                        [9.25, 1.0],
                        [9.50, 1.0],
                        [9.75, 1.0],
                        [10.00, 1.0],
                        [10.25, 1.0],
                        [10.50, 1.0],
                        [10.75, 1.0],
                        [11.00, 1.0],
                        [11.25, 1.0],
                        [11.50, 1.0],
                        [11.75, 1.0],

                        [12.00, 1.0],
                        [12.25, 1.0],
                        [12.50, 1.0],
                        [12.75, 1.0],
                        [13.00, 1.0],
                        [13.25, 1.0],
                    ],
                ],
                [
                    "assets/sounds/808-aristocrat/hat-open.wav",
                    [

                    ],
                ],
                [
                    "assets/sounds/808-aristocrat/cymbal-soft.wav",
                    [
                        [6.00, 1.0],
                        [6.50, 1.0],
                        [7.00, 1.0],

                        [13.50, 1.0],
                        [14.00, 1.0],
                        [14.50, 1.0],
                    ],
                ],
            ], knobs = [140.0, 15.0] },
            4.0,
        ],
    ] }

3M = { name = "Kick", type = "Oscilloscope" }
4M = { name = "Snare", type = "Oscilloscope" }
5M = { name = "Tom Mid", type = "Oscilloscope" }
6M = { name = "Hat Closed", type = "Oscilloscope" }
7M = { name = "Hat Open", type = "Oscilloscope" }
8M = { name = "Cymbal Soft", type = "Oscilloscope" }

9M = { name = "Bass Sequencer", type = "MultiSequencer", sequencers = [
        [
            { name = "Verse", type = "Sequencer", notes = [
                [65.41, 1.0, 0.25],
                [nan, 0.0, 2.75],

                [77.78, 1.0, 0.25],
                [nan, 0.0, 2.75],

                [130.81, 1.0, 0.5],
                [nan, 0.0, 1.5],
                [116.54, 1.0, 0.25],
                [nan, 0.0, 0.75],

                [103.83, 1.0, 2.0],
                [nan, 0.0, 1.0],

                [146.83, 1.0, 1.0],
                [116.54, 1.0, 1.0],
                [103.83, 1.0, 1.0],
            ], knobs = [140.0] },
            4.0,
        ],
        [
            { name = "Chorus", type = "Sequencer", notes = [
                [77.78, 1.0, 1.5],
                [nan, 0.0, 0.5],
                [65.41, 1.0, 1.0],

                [103.83, 1.0, 0.5],
                [103.83, 1.0, 0.5],
                [nan, 0.0, 0.5],
                [130.81, 1.0, 0.5],
                [nan, 0.0, 0.5],
                [146.83, 1.0, 0.5],

                [233.08, 1.0, 3.0],

                [nan, 0.0, 3.0],

                [261.63, 1.0, 1.0],
                [293.66, 1.0, 0.5],
                [261.63, 1.0, 1.0],
                [233.08, 1.0, 0.5],
            ], knobs = [140.0] },
            4.0,
        ],
    ] }

10M = { type = "EnvelopeGenerator", knobs = [0.01, 0.2, 0.5, 2.0] }
11M = { type = "Oscillator", func = "Triangle", knobs = [0.0, 110.0, 1.0, 0.0] }
12M = { type = "Oscillator", func = "Saw", knobs = [0.0, 110.0, 1.0, 0.25] }
13M = { type = "Multiplier" }
14M = { type = "Fuzz", knobs = [1000.0, 1.0, 1.0] }
15M = { type = "Compressor", knobs = [inf, 1.0, 0.0] }
16M = { type = "Delay", knobs = [0.1, 0.8, 0.4] }
17M = { type = "Equalizer", func = "LPF", knobs = [1_000.0, 10.0, 0.75] }
18M = { name = "Bass", type = "Oscilloscope" }

19M = { name = "Lead Sequencer", type = "MultiSequencer", sequencers = [
        [
            { name = "Verse", type = "Sequencer", notes = [
                [523.25, 1.0, 6.0],
                [622.25, 1.0, 3.0],
                [880.00, 1.0, 6.0],
            ], knobs = [140.0] },
            4.0,
        ],
        [
            { name = "Chorus", type = "Sequencer", notes = [
                [523.25, 1.0, 6.0],
                [880.00, 1.0, 3.0],
                [587.33, 1.0, 6.0],
            ], knobs = [140.0] },
            4.0,
        ],
    ] }

20M = { type = "EnvelopeGenerator", knobs = [1.0, 0.5, 0.5, 0.5 ] }
21M = { type = "Oscillator", func = "Saw", knobs = [0.0, 440.0, 1.0, 0.0] }
22M = { type = "Equalizer", func = "HPF", knobs = [900.0, 1000.0, 0.75] }
23M = { type = "Compressor", knobs = [inf, 0.1, 9.0] }
24M = { name = "Lead", type = "Oscilloscope" }

[patches]
1M0O = [
    "0M0I",
]
2M0O = [
    "1M0I",
    "3M0I",
]
2M1O = [
    "1M1I",
    "4M0I",
]
2M2O = [
    "1M2I",
    "5M0I",
]
2M3O = [
    "1M3I",
    "6M0I",
]
2M4O = [
    "1M4I",
    "7M0I",
]
2M5O = [
    "1M5I",
    "8M0I",
]
9M0O = [
    "11M1K",
    "12M1K",
]
9M1O = [
    "10M0I",
]
9M2O = [
    "10M1I",
]
10M0O = [
    "11M2K",
    "12M2K",
]
11M0O = [
    "13M0I",
]
12M0O = [
    "13M1I",
]
13M0O = [
    "14M0I",
]
14M0O = [
    "15M0I",
]
15M0O = [
    "16M0I",
]
16M0O = [
    "17M0I",
]
17M0O = [
    "1M6I",
    "18M0I",
]
19M0O = [
    "21M1K",
]
19M1O = [
    "20M0I",
]
19M2O = [
    "20M1I",
]
20M0O = [
    "21M2K",
]
21M0O = [
    "22M0I",
]
22M0O = [
    "23M0I",
]
23M0O = [
    "1M7I",
    "24M0I",
]
