[modules]
0M = { name = "Audio Out", type = "AudioOut", knobs = [1.0] }

1M = { type = "MidiIn" }
2M = { name = "Midi Scope", type = "Oscilloscope" }

3M = { name = "LFO 1", type = "Oscillator", func = "Triangle", knobs = [0.5, 10.0, 0.5, 0.0] }
4M = { name = "Scope 1", type = "Oscilloscope" }
5M = { name = "LFO 2", type = "Oscillator", func = "Sine", knobs = [1.0, 1000.0, 1.0, 0.0] }
6M = { name = "Scope 2", type = "Oscilloscope" }

7M = { name = "LFO 3", type = "Oscillator", func = "Sine", knobs = [0.0, 250.0, 1.0, 0.0] }
8M = { name = "Scope 3", type = "Oscilloscope" }
9M = { name = "Multiplier", type = "Multiplier" }
10M = { name = "Scope 4", type = "Oscilloscope" }

11M = { type = "Scaler", knobs = [1000.0] }

[patches]
1M0O = [
    "2M0I",
    "7M1K",
]
1M1O = [
    "7M2K",
]
1M2O = [
    "11M0I",
]
3M0O = [
    "4M0I",
    "5M2K",
]
5M0O = [
    # "0M0I",
    "6M0I",
    "9M0I",
]
7M0O = [
    # "0M0I",
    "8M0I",
    "9M1I",
]
9M0O = [
    "0M0I",
    "10M0I",
]
11M0O = [
    "3M1K",
]