[modules]
0M = { type = "AudioOut", knobs = [0.1] }
1M = { type = "AudioIn", knobs = [1.0] }
2M = { type = "Oscilloscope" }

3M = { type = "Oscillator", func = "Sine", knobs = [0.0, 880.0, 0.0, 0.0] }
4M = { type = "Oscilloscope" }

[patches]
1M0O = [
    "2M0I",
    "3M2K",
]
3M0O = [
    "0M0I",
    "4M0I",
]
