[info]
mode = "Video"

[modules]
0M = { type = "CompositeVideoOut" }

1M = { name = "Luma", type = "Oscillator", func = "Square", sync = "Horizontal", knobs = [0.5, 100.0, 0.5, 0.0] }
2M = { type = "Oscilloscope" }
3M = { name = "Chroma", type = "Oscillator", func = "Square", sync = "Vertical", knobs = [0.0, 10000.0, 1.0, 0.0] }
4M = { type = "Oscilloscope" }

[patches]
1M0O = [
    "0M0I",
    "2M0I",
]
3M0O = [
    "0M1I",
    "4M0I",
]
