[info]
name = "Are You With Me?"
author = "Louise Montalvo <louanmontalvo@gmail.com>"

[modules]
0M = { type = "AudioOut", knobs = [0.1] }

1M = { type = "Sequencer", notes = [
        [349.23, 1.0, 0.25],
        [440.00, 1.0, 0.25],
        [523.25, 1.0, 0.25],
        [659.26, 1.0, 0.25],
        [349.23, 1.0, 0.25],
        [440.00, 1.0, 0.25],
        [523.25, 1.0, 0.25],
        [659.26, 1.0, 0.25],
        [349.23, 1.0, 0.25],
        [440.00, 1.0, 0.25],
        [523.25, 1.0, 0.25],
        [659.26, 1.0, 0.25],
        [349.23, 1.0, 0.25],
        [440.00, 1.0, 0.25],
        [523.25, 1.0, 0.25],
        [659.26, 1.0, 0.25],

        [698.46, 1.0, 0.25],
        [659.26, 1.0, 0.25],
        [523.25, 1.0, 0.25],
        [440.00, 1.0, 0.25],
        [698.46, 1.0, 0.25],
        [659.26, 1.0, 0.25],
        [523.25, 1.0, 0.25],
        [440.00, 1.0, 0.25],
        [698.46, 1.0, 0.25],
        [659.26, 1.0, 0.25],
        [523.25, 1.0, 0.25],
        [440.00, 1.0, 0.25],
        [698.46, 1.0, 0.25],
        [659.26, 1.0, 0.25],
        [523.25, 1.0, 0.25],
        [440.00, 1.0, 0.25],
    ], knobs = [110.0] }
2M = { type = "Oscilloscope" }
3M = { type = "Oscilloscope" }
4M = { type = "Oscilloscope" }

5M = { type = "EnvelopeGenerator", knobs = [0.01, 0.05, 0.5, 0.1] }
6M = { type = "Oscilloscope" }

7M = { type = "Oscillator", func = "Saw", knobs = [0.0, 440.0, 1.0, 0.0] }
8M = { type = "Oscilloscope" }

[patches]
1M0O = [
    "2M0I",
    "7M1K",
]
1M1O = [
    "3M0I",
    "5M0I",
]
1M2O = [
    "4M0I",
    "5M1I",
]
5M0O = [
    "6M0I",
    "7M2K",
]
7M0O = [
    "0M0I",
    "8M0I",
]
